CREATE TABLE  "ADMINISTRATORS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"ADMIN_LEVEL" VARCHAR2(250) NOT NULL ENABLE, 
	"SCHOOL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(250) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(250) NOT NULL ENABLE, 
	"CREATE_ADMIN" VARCHAR2(1) NOT NULL ENABLE, 
	"EDIT_ADMIN" VARCHAR2(1) NOT NULL ENABLE, 
	"CREATE_VOLUNTEER" VARCHAR2(1) NOT NULL ENABLE, 
	"EDIT_VOLUNTEER" VARCHAR2(1) NOT NULL ENABLE, 
	"MERGE_ACCOUNT" VARCHAR2(1) NOT NULL ENABLE, 
	"DRILL" VARCHAR2(1) NOT NULL ENABLE, 
	"CREATE_LOCATION" VARCHAR2(1) NOT NULL ENABLE, 
	 CONSTRAINT "ADMIN_CON_CREATE_ADMIN" CHECK (CREATE_ADMIN IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMIN_CON_EDIT_ADMIN" CHECK (EDIT_ADMIN IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMIN_CON_MERGE" CHECK (MERGE_ACCOUNT IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMIN_CON_LOCATION" CHECK (CREATE_LOCATION IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMIN_CON_DRILL" CHECK (DRILL IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMIN_CON_CREATE_VOL" CHECK (CREATE_VOLUNTEER IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMIN_CON_EDIT_VOL" CHECK (EDIT_VOLUNTEER IN ('Y','N')) ENABLE, 
	 CONSTRAINT "ADMINISTRATORS_FK" FOREIGN KEY ("ID")
	  REFERENCES  "VOLUNTEERS" ("ID") ENABLE, 
	 CONSTRAINT "ADMINISTRATORS_FK_SCHOOL" FOREIGN KEY ("SCHOOL_ID")
	  REFERENCES  "LOCATIONS" ("SCHOOL_ID") ENABLE
   )
/


----------------------------------------------------------------------------------------------

 
CREATE TABLE  "FACULTY" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"DEPARTMENT" VARCHAR2(250) NOT NULL ENABLE, 
	"POSITION" VARCHAR2(250) NOT NULL ENABLE, 
	 CONSTRAINT "FACULTY_FK" FOREIGN KEY ("ID")
	  REFERENCES  "VOLUNTEERS" ("ID") ENABLE
   )
/


----------------------------------------------------------------------------------------------


CREATE TABLE  "HOURS_LOG" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"SCHOOL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DATE_TIME" DATE NOT NULL ENABLE, 
	"CHECKIN" TIMESTAMP (6) NOT NULL ENABLE, 
	"CHECKOUT" TIMESTAMP (6), 
	"HOURS" NUMBER(10,0), 
	 CONSTRAINT "HOURS_LOG_MIN_HOURS" CHECK ( "HOURS" >= 0) ENABLE, 
	 CONSTRAINT "HOURS_LOG_FK" FOREIGN KEY ("ID")
	  REFERENCES  "VOLUNTEERS" ("ID") ENABLE, 
	 CONSTRAINT "HOURS_LOG_SCHOOL_FK" FOREIGN KEY ("SCHOOL_ID")
	  REFERENCES  "LOCATIONS" ("SCHOOL_ID") ENABLE
   )
/


------------------------------------------------------------------------------------------------


CREATE TABLE  "LOCATIONS" 
   (	"SCHOOL_NAME" VARCHAR2(250) NOT NULL ENABLE, 
	"SCHOOL_TOTAL_HOURS" NUMBER(10,0) NOT NULL ENABLE, 
	"SCHOOL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "LOCATIONS_MIN_HOURS" CHECK ( "SCHOOL_TOTAL_HOURS" >= 0) ENABLE, 
	 CONSTRAINT "LOCATIONS_PK" PRIMARY KEY ("SCHOOL_ID") ENABLE
   )
/


-----------------------------------------------------------------------------------------------


CREATE TABLE  "STUDENTS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"MAJOR" VARCHAR2(250) NOT NULL ENABLE, 
	"COLLEGE" VARCHAR2(250) NOT NULL ENABLE, 
	 CONSTRAINT "STUDENTS_FK" FOREIGN KEY ("ID")
	  REFERENCES  "VOLUNTEERS" ("ID") ENABLE
   )
/


------------------------------------------------------------------------------------------------

 
CREATE TABLE  "VOLUNTEERS" 
   (	"ID" NUMBER(9,0) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(250) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(250) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(250) NOT NULL ENABLE, 
	"PHONE" NUMBER(10,0) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(250) NOT NULL ENABLE, 
	"TOTAL_HOURS" NUMBER(10,0) NOT NULL ENABLE, 
	"CHECKED_IN" VARCHAR2(1) NOT NULL ENABLE, 
	"GENDER" VARCHAR2(1), 
	"RACE/ETHNICITY" VARCHAR2(250), 
	 CONSTRAINT "VOLUNTEERS_PK" PRIMARY KEY ("ID") ENABLE, 
	 CONSTRAINT "VOLUNTEERS_UN_EMAIL" UNIQUE ("EMAIL") ENABLE, 
	 CONSTRAINT "VOLUNTEERS_MIN_HOURS" CHECK ( "TOTAL_HOURS" >= 0) ENABLE, 
	 CONSTRAINT "VOLUNTEERS_CHECKEDIN_YN" CHECK (CHECKED_IN IN ('Y','N')) ENABLE, 
	 CONSTRAINT "VOLUNTEERS_TYPE_CON" CHECK (TYPE IN ('Student','Faculty','Community','Admin')) ENABLE, 
	 CONSTRAINT "VOLUNTEERS_GENDER_CON" CHECK (GENDER IN ('M','F')) ENABLE
   )
/


CREATE OR REPLACE TRIGGER  "BI_VOLUNTEERS" 
  before insert on "VOLUNTEERS"               
  for each row  
begin   
    select "VOLUNTEERS_SEQ".nextval into :NEW.ID from dual; 
end; 

/
ALTER TRIGGER  "BI_VOLUNTEERS" ENABLE
/






